Repository codenitiva/restup-cli, pull requests merged in 2020-08, with the labels that each got.

#1 docs: fix unidentified link to restup-cli source code
  README.md
Labels: documentation

#2 feat: implement a more sophisticated way on file generation
  src/commands/controller.ts
  src/commands/middleware.ts
  src/commands/model.ts
  src/commands/router.ts
  src/templates/controller.txt
  src/templates/middleware.txt
  src/templates/requirements.txt
  src/templates/restup.config.template.txt
  src/templates/router.txt
  src/utils/command-controller.ts
  src/utils/config.ts
  src/utils/doctor.ts
  src/utils/php-fs.ts
  src/utils/php-generator.ts
  src/utils/types.ts
Labels: enhancement

#3 feat: add new command to init restup project
  README.md
  package.json
  src/commands/init.ts
  src/commands/start.ts
  src/index.d.ts
  src/utils/command-controller.ts
  yarn.lock
Labels: enhancement

#4 feat: release cli version 1.0.12
  README.md
  index.d.ts
  package.json
  src/commands/init.ts
  src/index.d.ts
  src/templates/config.txt
  src/utils/command-controller.ts
  src/utils/config.ts
  src/utils/doctor.ts
  src/utils/file-system.ts
  src/utils/path-helper.ts
  src/utils/php-fs.ts
  src/utils/types.ts
  tsconfig.json
Labels: enhancement

#5 fix: fix string casing error
  README.md
  package.json
  src/utils/string-case.ts
Labels: bug
